# Generated by Django 4.1.6 on 2023-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_password_text_alter_user_email_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_text',
            field=models.CharField(max_length=21),
        ),
    ]
